-- Ceter Technologies bootstrap seed
--
-- This file intentionally does not insert catalogue records.
-- Products, categories, brands, banners, homepage sections, and services should
-- come from admin CRUD or clean imports, not from demo/sample seed data.
--
-- Safe to run against an empty catalogue.
